### ISSUE TITLE
BoxHeaders parsing strangely

### ISSUE THREAD

**Issue by momo-the-monster** [aosoft/VR180MeshProjection#2]
I've tried two different videos, and they each fail at finding the "moov" header.

My first video finds the following headers:

- "ftyp"
- "mdat"
- "q?7?"

and then returns null.

My second video finds a single header called "?\b?U"
and then returns null.

**Comment by aosoft** [comment]
Are you using "Lenovo Mirage Camera" ?
This sample is based on MP4 taken with Mirage Camera.

**Comment by momo-the-monster** [comment]
Yes, I'm using the Lenovo Mirage Camera.
here are two examples of MP4s from the camera which throw errors when I try to parse them:

- [long.vr.mp4](https://drive.google.com/open?id=1Y6UQgf4o2NO5u4hbSzf4vajF8mRWDEYO)
- [short.vr.mp4](https://drive.google.com/open?id=1kBsC73CgDPn7SOZMtPPDCNUtAnNwbB8b)

**Comment by aosoft** [comment]
These files were not taken with Mirage Camera. I think that they were converted by some application.
This sample program requires an original file.

**Comment by momo-the-monster** [comment]
Yes, they were taken with the Mirage camera. I copied them directly from
the SD card. I only renamed them for easier testing.
